### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by AlexProgrammerDE** [ionar2/salhack#250]
**Describe the bug**
Used scaffolding, broke block, game crashed

**To Reproduce**
1. Used scaffolding
2. broke block
3. game crashed

**Expected behavior**
No crash?

**Logs**

<details>

``````
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (salhack-github-2.04-release.jar)
  ySyy (wwe 1.12.2..jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/28/20 9:45 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at me.ionar.salhack.util.BlockInteractionHelper.valid(BlockInteractionHelper.java:205)
	at me.ionar.salhack.module.world.ScaffoldModule.lambda$new$1(ScaffoldModule.java:181)
	at me.ionar.salhack.module.world.ScaffoldModule$$Lambda$351/944177488.invoke(Unknown Source)
	at me.zero.alpine.fork.listener.Listener.invoke(Listener.java:98)
	at me.zero.alpine.fork.bus.EventManager.lambda$post$5(EventManager.java:79)
	at me.zero.alpine.fork.bus.EventManager$$Lambda$418/1312502816.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.fork.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.client.entity.EntityPlayerSP.handler$OnPreUpdateWalkingPlayer$zza000(EntityPlayerSP.java:1339)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ionar.salhack.util.BlockInteractionHelper.valid(BlockInteractionHelper.java:205)
	at me.ionar.salhack.module.world.ScaffoldModule.lambda$new$1(ScaffoldModule.java:181)
	at me.ionar.salhack.module.world.ScaffoldModule$$Lambda$351/944177488.invoke(Unknown Source)
	at me.zero.alpine.fork.listener.Listener.invoke(Listener.java:98)
	at me.zero.alpine.fork.bus.EventManager.lambda$post$5(EventManager.java:79)
	at me.zero.alpine.fork.bus.EventManager$$Lambda$418/1312502816.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.fork.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.client.entity.EntityPlayerSP.handler$OnPreUpdateWalkingPlayer$zza000(EntityPlayerSP.java:1339)
	at net.minecraft.client.entity.EntityPlayerSP.func_175161_p(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:196)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 2805
	Entity Name: Pistonmaster
	Entity's Exact location: -0.36, 68.00, 805.89
	Entity's Block location: World: (-1,68,805), Chunk: (at 15,4,5 in -1,50; contains blocks -16,0,800 to -1,255,815), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 771081480 bytes (735 MB) / 1107296256 bytes (1056 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                          | Signature |
	|:------ |:------------- |:------------ |:------------------------------- |:--------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                   | None      |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                   | None      |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar   | None      |
	| LCHIJA | forge         | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar   | None      |
	| LCHIJA | lunatriuscore | ${version}   | salhack-github-2.04-release.jar | None      |
	| LCHIJA | schematica    | ${version}   | salhack-github-2.04-release.jar | None      |
	| LCHIJA | salhack       | 2.03         | salhack-github-2.04-release.jar | None      |
	| LCHIJA | wwe           | 3.0.4        | wwe 1.12.2..jar                 | None      |

	Loaded coremods (and transformers): 
MixinLoaderForge (salhack-github-2.04-release.jar)
  
ySyy (wwe 1.12.2..jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000' Renderer: 'Radeon RX 570 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Radeon RX 570 Series GL version 4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics 
``````

**Additional context**
Got wwe too

**Comment by Vaixe24** [comment]
pretty sure i fixed this, will be releasing soon

**Comment by hirak-svg** [comment]
yes this is soon 3 months nice
