### ISSUE TITLE
when i launch salhack it crashes right away. here is the crash report

### ISSUE THREAD

**Issue by bumba420** [ionar2/salhack#279]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (salhack-github-2.05-release.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/7/20 6:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SalHack (salhack)
Caused by: java.lang.NullPointerException
	at me.ionar.salhack.managers.DiscordManager.disable(DiscordManager.java:51)
	at me.ionar.salhack.module.misc.DiscordRPCModule.onDisable(DiscordRPCModule.java:53)
	at me.ionar.salhack.module.Module.toggle(Module.java:109)
	at me.ionar.salhack.preset.Preset.initValuesForMod(Preset.java:219)
	at me.ionar.salhack.managers.ModuleManager.lambda$Init$1(ModuleManager.java:195)
	at me.ionar.salhack.managers.ModuleManager$$Lambda$355/293394374.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at me.ionar.salhack.managers.ModuleManager.Init(ModuleManager.java:193)
	at me.ionar.salhack.main.SalHack.Init(SalHack.java:46)
	at me.ionar.salhack.SalHackMod.init(SalHackMod.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 509304808 bytes (485 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                          | Signature                                |
	|:----- |:------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft     | 1.12.2       | minecraft.jar                   | None                                     |
	| LCHI  | mcp           | 9.42         | minecraft.jar                   | None                                     |
	| LCHI  | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge         | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | lunatriuscore | ${version}   | salhack-github-2.05-release.jar | None                                     |
	| LCHI  | schematica    | ${version}   | salhack-github-2.05-release.jar | None                                     |
	| LCHE  | salhack       | 2.05         | salhack-github-2.05-release.jar | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (salhack-github-2.05-release.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GT 710/PCIe/SSE2'

**Comment by Vaixe24** [comment]
Hi there, please delete your salhack folder from your .minecraft, and then make sure you have downloaded the latest update from #public_releases. Ensure you don't have any other older mod folders. Let me know if this fixes the issue, and also please try other mods/clients with forge to see if you can run forge as a whole. Thank you!

Also to note, you have the rpc crash. taking these steps should fix everything.


If you have any more questions, comments or concerns, contact @Vaixe24 on discord.

**Comment by Ravenster2** [comment]
I have the same problem. Minecraft crashes as soon as it launches. I run Salhack in forge along with impact and optifine. It works when I remove Salhack from the "mods" folder. I tried using Salhack 2.04 but that crashed due to "ticking entity" whenever I use crystal aura.

**Comment by hirak-svg** [comment]
let the discord rpc turn on..... should it fix issue.....and also do not turn on full hud

**Comment by zisis912** [comment]
sounds like forcing people to advertise your client through their discord account to let them not crash to me.
