### ISSUE TITLE
SalHack Crashes on Launch (bruh)

### ISSUE THREAD

**Issue by Prixsen** [ionar2/salhack#289]
**Describe the bug**
Minecraft crashes when I launch it with SalHack in my Mods folder. Without SalHack, Forge runs just fine with Optifine and a World Downloader for Forge. Future Client even runs fine in conjunction with the previously mentioned.

**To Reproduce**

1. Download the latest release of SalHack
2. Move the SalHack .jar to the Mods folder
3. Create an installation utilizing the correct version of Forge
4. Click "Play"
5. When Minecraft crashes for the 500th time, you die a bit inside

**Expected behavior**
I expected Minecraft to launch without crashing.

**Screenshots**
I have many crash reports. Here is one of them:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (salhack-2.05-release.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/16/20 3:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SalHack (salhack)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Andre\OneDrive\Desktop\runtime\jre-x64\bin\dcpr.dll: The cloud file provider is not running
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.dc.pr.PathFiller$1.run(PathFiller.java:434)
	at sun.dc.pr.PathFiller$1.run(PathFiller.java:432)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.dc.pr.PathFiller.<clinit>(PathFiller.java:431)
	at sun.dc.pr.Rasterizer.<clinit>(Rasterizer.java:77)
	at sun.dc.DuctusRenderingEngine.getRasterizer(DuctusRenderingEngine.java:365)
	at sun.dc.DuctusRenderingEngine.getAATileGenerator(DuctusRenderingEngine.java:397)
	at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:152)
	at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:68)
	at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)
	at sun.java2d.pipe.ValidatePipe.fill(ValidatePipe.java:160)
	at sun.java2d.SunGraphics2D.fill(SunGraphics2D.java:2527)
	at org.newdawn.slick.font.effects.ColorEffect.draw(ColorEffect.java:43)
	at org.newdawn.slick.font.GlyphPage.renderGlyph(GlyphPage.java:203)
	at org.newdawn.slick.font.GlyphPage.loadGlyphs(GlyphPage.java:166)
	at org.newdawn.slick.UnicodeFont.loadGlyphs(UnicodeFont.java:376)
	at org.newdawn.slick.UnicodeFont.loadGlyphs(UnicodeFont.java:325)
	at me.ionar.salhack.util.render.SalFontRenderer.<init>(SalFontRenderer.java:53)
	at me.ionar.salhack.managers.FontManager.Load(FontManager.java:20)
	at me.ionar.salhack.main.SalHack.Init(SalHack.java:44)
	at me.ionar.salhack.SalHackMod.init(SalHackMod.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.1.7-SNAPSHOT
	Minecraft version: Minecraft 1.12.2 (1.12.2-forge1.12.2-14.23.5.2847/fml,forge/Forge)
	Expected version: 1.12.2
	Protocol version: 340
	Data version: 1343
	File location: ~~ERROR~~ IllegalArgumentException: URI is not hierarchical
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:351)
	at wdl.WDL.addInfoToCrash(WDL.java:1497)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:381)
	at net.minecraft.crash.CrashReport.handler$onCrashReportPopulateEnvironment$zbp000(CrashReport.java:532)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraftforge.fml.client.FMLClientHandler.haltGame(FMLClientHandler.java:312)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:349)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ea30797 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ea30797 (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@1f7b1d6a
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	thePlayer: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: WorldDownloaderERROR
	baseFolderName: WorldDownloaderERROR

-- World Downloader Mod - Base properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	-: empty

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 339356880 bytes (323 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                        | Signature |
	|:----- |:------------- |:------------ |:----------------------------- |:--------- |
	| LCHI  | minecraft     | 1.12.2       | minecraft.jar                 | None      |
	| LCHI  | mcp           | 9.42         | minecraft.jar                 | None      |
	| LCHI  | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHI  | forge         | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHI  | lunatriuscore | 1.2.0.42     | salhack-2.05-release.jar      | None      |
	| LCHI  | schematica    | 1.8.0.169    | salhack-2.05-release.jar      | None      |
	| LCHE  | salhack       | 2.05         | salhack-2.05-release.jar      | None      |

	Loaded coremods (and transformers): 
MixinLoaderForge (salhack-2.05-release.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 446.14' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Additional context**
I've been trying to get SalHack to work all day, yet nothing I do seems to change the outcome.

**Comment by Prixsen** [comment]
Ok, I figured out what the problem was. (It wasn't obvious btw)

**Comment by TeaAndSugar-1** [comment]
how did you fix the issue?
