### ISSUE TITLE
Crashing when joining singleplayer/multiplayer and loading the map

### ISSUE THREAD

**Issue by st3ph4nnn** [ionar2/salhack#304]
**Describe the bug**
Whenever i load salhack (1.12.2 Forge, no other mods just salhack) and i go in singleplayer or multiplayer to test it out, when the map loades and when i join i just crash, does anyone know how to fix it?

**To Reproduce**
1. Open minecraft with salhack 1.12.2 (forge)
2. join singleplayer/multiplayer

**Expected behavior**
it should not crash i guess?

**Screenshots**
https://i.postimg.cc/rw77HJBn/screenshot-1046.png 

**Additional context**
This is the error i get in the console, `java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:450)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:129)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:93)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)` 
also i give minecraft 6GB of ram to run, so that shouldnt be a problem.

**Comment by TheRedRipper** [comment]
same. please fix
